### ISSUE TITLE
Unreasonable return in vite plugin config hook result in build error

### ISSUE THREAD

**Issue by LiHDong** [antfu/vite-plugin-package-config#1]
As you can see, your plugin will return the whole config used in config:
https://github.com/antfu/vite-plugin-package-config/blob/cdb5f47e5817e15420d704d2e08db5b052116878/src/index.ts#L46
which is totally diffenent from the [doc](https://vitejs.dev/guide/api-plugin.html#config).And this will make the plugin list in `build.rollupOptions.plugins` duplicate, which cause rollup throw `DUPLICATE_PLUGIN_NAME` exception.

**Comment by antfu** [comment]
Nice spot. Mind sending a PR? Thanks
